<?php 
    // Config plugins
    $labels = array(
        'name' => _x('All Rental', 'Post type general name', 'textdomain'),
        'singular_name' => _x('Rental Settings', 'Post type singular name', 'textdomain'),
        'menu_name' => _x('Rental Settings', 'Admin Menu text', 'textdomain'),
        'name_admin_bar' => _x('Rental', 'Add New on Toolbar', 'textdomain'),
        'add_new' => __('Add New Rental', 'textdomain'),
        'add_new_item' => __('Add New Rental', 'textdomain'),
        'new_item' => __('New Rental', 'textdomain'),
        'edit_item' => __('Edit Rental', 'textdomain'),
        'view_item' => __('View Rental', 'textdomain'),
        'all_items' => __('All Rental', 'textdomain'),
        'search_items' => __('Search Rental', 'textdomain'),
        'parent_item_colon' => __('Parent Rental:', 'textdomain'),
        'not_found' => __('Not content...', 'textdomain'),
        'not_found_in_trash' => __('Not found in Trash.', 'textdomain'),
        'featured_image' => _x('Rental Home Principal Image', 'Overrides the “Featured Image” phrase for this post type. Added in 4.3', 'textdomain'),
        'set_featured_image' => _x('Add Image', 'Overrides the “Set featured image” phrase for this post type. Added in 4.3', 'textdomain'),
        'remove_featured_image' => _x('Remove image', 'Overrides the “Remove featured image” phrase for this post type. Added in 4.3', 'textdomain'),
        'use_featured_image' => _x('Use as cover image', 'Overrides the “Use as featured image” phrase for this post type. Added in 4.3', 'textdomain'),
        'archives' => _x('All Rental archives', 'The post type archive label used in nav menus. Default “Post Archives”. Added in 4.4', 'textdomain'),
        'insert_into_item' => _x('Insert into Rental', 'Overrides the “Insert into post”/”Insert into page” phrase (used when inserting media into a post). Added in 4.4', 'textdomain'),
        'uploaded_to_this_item' => _x('Uploaded to this Rental', 'Overrides the “Uploaded to this post”/”Uploaded to this page” phrase (used when viewing media attached to a post). Added in 4.4', 'textdomain'),
        'filter_items_list' => _x('Filter Rental list', 'Screen reader text for the filter links heading on the post type listing screen. Default “Filter posts list”/”Filter pages list”. Added in 4.4', 'textdomain'),
        'items_list_navigation' => _x('Rental list navigation', 'Screen reader text for the pagination heading on the post type listing screen. Default “Posts list navigation”/”Pages list navigation”. Added in 4.4', 'textdomain'),
        'items_list' => _x('Rental list', 'Screen reader text for the items list heading on the post type listing screen. Default “Posts list”/”Pages list”. Added in 4.4', 'textdomain'),
    );