<?php 
    // Config plugins
    $labels = array(
        'name' => _x('All Home', 'Post type general name', 'textdomain'),
        'singular_name' => _x('Home Config', 'Post type singular name', 'textdomain'),
        'menu_name' => _x('Home Config', 'Admin Menu text', 'textdomain'),
        'name_admin_bar' => _x('Home', 'Add New on Toolbar', 'textdomain'),
        'add_new' => __('Add New Home', 'textdomain'),
        'add_new_item' => __('Add New Home', 'textdomain'),
        'new_item' => __('New Home', 'textdomain'),
        'edit_item' => __('Edit Home', 'textdomain'),
        'view_item' => __('View Home', 'textdomain'),
        'all_items' => __('All Home', 'textdomain'),
        'search_items' => __('Search Home', 'textdomain'),
        'parent_item_colon' => __('Parent Home:', 'textdomain'),
        'not_found' => __('Not content...', 'textdomain'),
        'not_found_in_trash' => __('Not found in Trash.', 'textdomain'),
        'featured_image' => _x('Home Cover Image', 'Overrides the “Featured Image” phrase for this post type. Added in 4.3', 'textdomain'),
        'set_featured_image' => _x('Add Image', 'Overrides the “Set featured image” phrase for this post type. Added in 4.3', 'textdomain'),
        'remove_featured_image' => _x('Remove image', 'Overrides the “Remove featured image” phrase for this post type. Added in 4.3', 'textdomain'),
        'use_featured_image' => _x('Use as cover image', 'Overrides the “Use as featured image” phrase for this post type. Added in 4.3', 'textdomain'),
        'archives' => _x('Home Home archives', 'The post type archive label used in nav menus. Default “Post Archives”. Added in 4.4', 'textdomain'),
        'insert_into_item' => _x('Insert into Home', 'Overrides the “Insert into post”/”Insert into page” phrase (used when inserting media into a post). Added in 4.4', 'textdomain'),
        'uploaded_to_this_item' => _x('Uploaded to this Home', 'Overrides the “Uploaded to this post”/”Uploaded to this page” phrase (used when viewing media attached to a post). Added in 4.4', 'textdomain'),
        'filter_items_list' => _x('Filter Home list', 'Screen reader text for the filter links heading on the post type listing screen. Default “Filter posts list”/”Filter pages list”. Added in 4.4', 'textdomain'),
        'items_list_navigation' => _x('Home Home list navigation', 'Screen reader text for the pagination heading on the post type listing screen. Default “Posts list navigation”/”Pages list navigation”. Added in 4.4', 'textdomain'),
        'items_list' => _x('Home Home list', 'Screen reader text for the items list heading on the post type listing screen. Default “Posts list”/”Pages list”. Added in 4.4', 'textdomain'),
    );